### PR TITLE
Adding functions to work with duplicate songs

### PR DESCRIPTION
**Pull request by karelkryda**
- **removeDuplicates** - removing duplicate songs from the queue - void
- **isUnique** - check if the song is unique (if is not already in the queue) - boolean
- **getUnique** - returns only songs that are not yet queued - track array (maybe I mistaken the return value in TypeScript)

### CODE REVIEW

**Comment by ItsAuric** [comment]
Have you verified the functions work by testing them? If you haven't, test them Solaris knows if it's mergeable with no errors/bugs,

**Comment by karelkryda** [comment]
> Have you verified the functions work by testing them? If you haven't, test them Solaris knows if it's mergeable with no errors/bugs.

I wrote them in JavaScript and they work there. I just don't know if I rewrote them correctly in TypeScript. How can I test it?

**Comment by ItsAuric** [comment]
I've never used TypeScript, you'd have to get Solaris to assist.

**Comment by karelkryda** [comment]
> I've never used TypeScript, you'd have to get Solaris to assist.

Yeah, I never used TypeScript too. Should I dm Solaris, or normally write on support  channel on Discord?

**Comment by ItsAuric** [comment]
I assume he'd rather speak in #code-support.

**Comment by acollierr17** [comment]
This PR is quite opinionated for Erela. Something like this could be added to your own codebase. This helps some people, but not others when it comes to duplicate tracks in the queue.

**Pull request closed without merging**
