### PR TITLE
Added method param

### PR DESCRIPTION
**Pull request by karelkryda**
specify method (POST or GET)

### CODE REVIEW

**Comment by acollierr17** [comment]
Can you throw this, #98 and #99 all into one PR? Multiple PRs that are all related to each other aren't necessary. If you're new to Git (and GitHub) and need some guidance, feel free to ask!

**Comment by karelkryda** [comment]
@acollierr17 sorry, but my GitHub is broken. How can I do it?

**Comment by karelkryda** [comment]
OK, done @acollierr17

**Comment by acollierr17** [comment]
I'm going to close this PR, #98 and #99 because you actually changed files in the `/dist` folder. These files are **not** the ones you should be modifying. The files in the `/src` directory are the actual files of the project to be modified. The files in the `/dist` folder are used whenever you import or require the package in a Node.js application.

**Comment by acollierr17** [comment]
This project is TypeScript knowledge, so if you're lacking in experience with TypeScript, it's actually not that difficult to get into due to the fact that it's only a superset of JavaScript. This means all of the paradigms you apply in JavaScript can be applied to TypeScript.

The [TypeScript Handbook](https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes.html) might be useful for you.

**Pull request closed without merging**
